version: '2'

services:

    applications:
        image: tianon/true
        volumes:
            - ../:/var/www
    php-fpm:
        build:
            context: ./php-fpm
            args:
                - INSTALL_XDEBUG=true
            dockerfile: Dockerfile-70
        volumes_from:
                    - applications
        expose:
            - "9000"

    nginx:
        build:
            context: ./nginx
            args:
                - PHP_UPSTREAM=php-fpm
        volumes:
            - ./logs/nginx/:/var/log/nginx
            - ./nginx/sites/:/etc/nginx/sites-available
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm

    mariadb:
        build: ./mariadb
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
            MYSQL_ROOT_PASSWORD: wordpress